export const Events = [
	{
		id: 1,
		name: 'Event 1',
		date: '2022-07-23',
		time: '7 pm',
		venue: 'Oskar Bar and Grills',
		location: 'Jhamsikhel, Kathmandu',
		organizer: 'organizer 1',
		image: 'image 1',
		ticket_price: 400,
		contact: '9812343535',
		description: '',
	},
	{
		id: 2,
		name: 'The Hatiya',
		date: '2022-08-28',
		time: '6 pm onwards',
		venue: 'Bittersroom Cafe',
		location: 'Butwal',
		organizer: 'Hippiness',
		image: 'image 3',
		ticket_price: 0,
		contact: '98123436677',
		description: 'support local vendors',
	},
	{
		id: 3,
		name: 'Event 3',
		start_date: '2022-09-12',
		end_date: '2022-10-12',
		time: '10 am - 5 pm',
		venue: 'Nepal Arts Council',
		location: 'Babarmahal, Kathmandu',
		organizer: 'organizer 3',
		image: 'image 3',
		ticket_price: 0,
		contact: '98123454264',
		description: 'dispaly of arts by various artists',
	},
]
